version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

  jobs:
    post_create_environment:
      - python -m pip install uv
    post_install:
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --all-extras --group docs --link-mode=copy

sphinx:
  builder: dirhtml
  configuration: "docs/conf.py"
  fail_on_warning: true
