version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - pip install poetry
      - poetry config virtualenvs.create false
      - poetry install --only docs
      - poetry run poetry-dynamic-versioning

sphinx:
  builder: dirhtml
  configuration: "docs/conf.py"
  fail_on_warning: true
