version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - python -m pip install poetry
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --only main,docs
      - poetry run poetry-dynamic-versioning

sphinx:
  builder: dirhtml
  configuration: "docs/conf.py"
  fail_on_warning: true
